apiVersion: v1
kind: Secret
metadata:
  name: pg-admin-secrets
type: Opaque
data:
  # Base64 String: superman@google.com = cG9zdGdyZXM=
  PG_USER_EMAIL: c3VwZXJtYW5AZ29vZ2xlLmNvbQ==
  # Mok.12345
  DB_PASSWORD: TW9rLjEyMzQ1